# Generated by Django 5.1.3 on 2024-11-25 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_options_alter_article_categori_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='reactions',
            options={'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='users',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador del artículo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article_comments', to='blog.comment', verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='categori',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de comentario'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='article',
            field=models.ManyToManyField(blank=True, to='blog.article', verbose_name='Artículos con reacciones'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que reaccionaron'),
        ),
    ]
