# Generated by Django 5.1.3 on 2024-11-25 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_options_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='reactions',
            options={'verbose_name': 'reacion', 'verbose_name_plural': 'reaciones'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article_comments', to='blog.comment', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='categori',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='article',
            field=models.ManyToManyField(blank=True, to='blog.article', verbose_name='numero de likes'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
