# Generated by Django 5.1.3 on 2024-11-14 22:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='fecha')),
                ('update_at', models.DateField(auto_now=True, null=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('categori', models.ManyToManyField(blank=True, to='blog.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('image', models.ImageField(default='null', upload_to='article', verbose_name='Imagen')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('update_at', models.DateField(auto_now=True, null=True, verbose_name='fecha')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('categori', models.ManyToManyField(blank=True, to='blog.category', verbose_name='categoria')),
                ('comment', models.ManyToManyField(blank=True, related_name='article_comments', to='blog.comment', verbose_name='comentario')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_articles', to='blog.comment', verbose_name='numero de likes')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ManyToManyField(blank=True, to='blog.article', verbose_name='numero de likes')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'reacion',
                'verbose_name_plural': 'reaciones',
            },
        ),
    ]
