# Generated by Django 5.1.3 on 2024-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to='article', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
