# Generated by Django 5.1.3 on 2024-11-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='article',
            name='categori',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article_comments', to='blog.comment', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de publicación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='blog.comment', verbose_name='Número de likes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha y hora de actualización'),
        ),
    ]
